set_property PACKAGE_PIN V19 [get_ports {LED[3]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN U18 [get_ports ten]
set_property PACKAGE_PIN T18 [get_ports rst]
set_property PACKAGE_PIN W19 [get_ports five]
set_property PACKAGE_PIN T17 [get_ports fifty]
set_property PACKAGE_PIN U17 [get_ports cancel]
set_property IOSTANDARD LVCMOS33 [get_ports fifty]
set_property IOSTANDARD LVCMOS33 [get_ports five]
set_property IOSTANDARD LVCMOS33 [get_ports cancel]
set_property IOSTANDARD LVCMOS33 [get_ports ten]

