set_property SRC_FILE_INFO {cfile:{E:/Code/Vivado/Final Project/sensor_test/sensor_test.srcs/constrs_1/new/yccc.xdc} rfile:../../../sensor_test.srcs/constrs_1/new/yccc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports in]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports out]
