set_property IOSTANDARD LVCMOS33 [get_ports {digit[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {left[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {motor[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {right[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {signal[0]}]
set_property PACKAGE_PIN W4 [get_ports {PA[3]}]
set_property PACKAGE_PIN V4 [get_ports {PA[2]}]
set_property PACKAGE_PIN U4 [get_ports {PA[1]}]
set_property PACKAGE_PIN U2 [get_ports {PA[0]}]
set_property PACKAGE_PIN W7 [get_ports {digit[7]}]
set_property PACKAGE_PIN V5 [get_ports {digit[6]}]
set_property PACKAGE_PIN W6 [get_ports {digit[5]}]
set_property PACKAGE_PIN U7 [get_ports {digit[4]}]
set_property PACKAGE_PIN U5 [get_ports {digit[3]}]
set_property PACKAGE_PIN U8 [get_ports {digit[2]}]
set_property PACKAGE_PIN V8 [get_ports {digit[1]}]
set_property PACKAGE_PIN V7 [get_ports {digit[0]}]
set_property PACKAGE_PIN M2 [get_ports {left[1]}]
set_property PACKAGE_PIN L3 [get_ports {left[0]}]
set_property PACKAGE_PIN J3 [get_ports {motor[1]}]
set_property PACKAGE_PIN J2 [get_ports {motor[0]}]
set_property PACKAGE_PIN J1 [get_ports {right[1]}]
set_property PACKAGE_PIN G3 [get_ports {signal[2]}]
set_property PACKAGE_PIN H2 [get_ports {signal[1]}]
set_property PACKAGE_PIN K2 [get_ports {signal[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports rst]




set_property PACKAGE_PIN L2 [get_ports {right[0]}]

set_property PACKAGE_PIN B15 [get_ports trig]
set_property PACKAGE_PIN B16 [get_ports echo]
set_property IOSTANDARD LVCMOS33 [get_ports echo]
set_property IOSTANDARD LVCMOS33 [get_ports trig]

set_property PACKAGE_PIN U14 [get_ports stop]
set_property IOSTANDARD LVCMOS33 [get_ports stop]
